app/routes.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, flash

import config
from app.form import PersonForm, RecipientForm
from app.models import Person, Recipient
from app.utils import sendmail, version

main_bp = Blueprint('main', __name__, template_folder='templates')


@main_bp.context_processor
def global_variables():
    values = {}
    values["app_name"] = config.APP_NAME
    values["version"] = version()
    return values


@main_bp.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")


@main_bp.route("/person/add", methods=["GET", "POST"])
def person_add():
    person_form = PersonForm()
    recipient_list = Recipient.query.all()
    print('<person_add Method>', request.method)
    if request.method == 'POST':
        data = request.form
        try:
            person_data = {}
            if data:
                for d in data:
                    print("key {}, type {}, data {}".format(d, type(data.getlist(d)), data.getlist(d)))
                    if hasattr(Person, d) and data[d] != '':
                        if len(data.getlist(d)) == 1:
                            person_data[d] = data[d]
                        else:
                            person_data[d] = '; '.join(data.getlist(d))

            # Convert Date string to python datetime object
            person_data['arrival_date'] = datetime.strptime(person_data['arrival_date'], '%Y-%m-%d').date()
            if 'departure_date' in person_data.keys():
                person_data['departure_date'] = datetime.strptime(person_data['departure_date'], '%Y-%m-%d').date()

            new_person = Person(**person_data)
            new_person.save_to_db()
            id = new_person.id_person
            print('<person_add id>', id)
            print('<person_row>', new_person)

            flash('Merci pour cette participation')

            new_person_dict = dict((col, getattr(new_person, col)) for col in new_person.__table__.columns.keys())
            print('<new_person_dict 1>', type(new_person_dict), new_person_dict)

            for k, v in new_person_dict.items():
                print(k, v)
                if new_person_dict[k] == None:
                    print(k)
                    new_person_dict[k] = 'Non défini'

            print('<new_person_dict 2>', new_person_dict)

            for recipient in recipient_list:
                sendmail(recipient.subject, recipient.body, recipient.email, new_person_dict)
            sendmail("Déclaration d'une nouvelle arrivée",
                     "Votre déclaration pour {} {} a bien été transmise. \n\n[Ceci est un message automatique]".format(
                         new_person.name, new_person.surname), new_person.email_referent, person_data)

        except Exception as e:
            flash(e)
            print("<person_add error>", e)
            return render_template("person_form.html", form=person_form, recipients=recipient_list)

        return redirect(url_for('main.person', id=id))

    return render_template("person_form.html", form=person_form, recipients=recipient_list)


@main_bp.route('/person/<int:id>')
def person(id):
    pers = Person.query.filter_by(id_person=id).first()
    person_dict = dict((col, getattr(pers, col)) for col in pers.__table__.columns.keys())
    print('TYPE', type(person_dict))
    return render_template("person.html", person=person_dict)


@main_bp.route('/persons')
def persons():
    try:
        pers = Person.query.all()
        persons_dict = []
        for p in pers:
            p_dict = dict((col, getattr(p, col)) for col in p.__table__.columns.keys())
            persons_dict.append(p_dict)
        return render_template("persons.html", persons=persons_dict)
    except Exception as e:
        flash('Aucune donnée')
        print("<persons error>", e)
        return render_template("problem.html")


@main_bp.route("/recipient/add", methods=["GET", "POST"])
def recipient_add():
    recipient_form = RecipientForm()

    var_list = []
    for a in Person.__table__.columns:
        print('att', a.doc, a.name)
        d = {}
        d['doc'] = a.doc
        d['var'] = a.name
        var_list.append(d)

    if request.method == 'POST':
        data = request.form
        try:
            recipient_data = {}
            if data:
                for d in data:
                    print(d, data[d])
                    if hasattr(Recipient, d):
                        recipient_data[d] = data[d]

            new_recipient = Recipient(**recipient_data)
            new_recipient.save_to_db()

        except Exception as e:
            print("<add_recipient error>", e)
            flash(e)
            return render_template("recipient_form.html", form=recipient_form, var=var_list)

        return redirect(url_for('main.recipients_list'))

    return render_template("recipient_form.html", form=recipient_form, var=var_list)


@main_bp.route("/recipient/edit/<id>", methods=["GET", "POST"])
def recipient_edit(id=None):
    recipient = Recipient.query.get(id)

    recipient_form = RecipientForm(obj=recipient)
    recipient_form.populate_obj(recipient)

    var_list = []
    for a in Person.__table__.columns:
        d = {}
        d['doc'] = a.doc
        d['var'] = a.name
        var_list.append(d)

    if request.method == 'POST':
        data = request.form
        try:
            recipient_data = {}
            if data:
                for d in data:
                    print(d, data[d])
                    if hasattr(Recipient, d):
                        recipient_data[d] = data[d]

            recipient.update(recipient_data)
            recipient.update_to_db()

        except Exception as e:
            print("<add_recipient error>", e)
            flash(e)
            return render_template("recipient_form.html", form=recipient_form, var=var_list)

        return redirect(url_for('main.recipients_list'))

    return render_template("recipient_form.html", form=recipient_form, var=var_list)


@main_bp.route('/recipients')
def recipients_list():
    try:
        recipients = Recipient.query.all()
        recipients_dict = []
        for p in recipients:
            p_dict = dict((col, getattr(p, col)) for col in p.__table__.columns.keys())
            recipients_dict.append(p_dict)
        return render_template("recipients.html", recipients=recipients_dict)
    except Exception as e:
        print("<recipients error>", e)
        return render_template("problem.html")

app/templates/_helpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class=errors>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

app/templates/home.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<h1><i class="fa fa-home"></i>{% block title %}Accueil{% endblock %}</h1>
{%endblock%}

<style>
    .jumbotron {
        height: 100%;
        width: 100%;
    }

    .container {
        width: 1025px;
    }

    .jumbotron .container {
        max-width: 100%;
    }
</style>

<div class="jumbotron">
    <div class="container text-center">
        <h1>Plateforme de déclaration des nouveaux arrivants au sein des salariés de la LPO AuRA</h1>
        <div class="row">
            <div class="col text-center">
                <a class="btn btn-success btn-lg" href="{{ url_for('main.person_add') }}"><i
                        class="fa fa-user-plus"></i> Déclarer une nouvelle
                    arrivée</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>{{ app_name }} | {% block title %}Ajout d'un nouvel arrivant{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/datatables.min.css') }}">


    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">
    <!-- Scripts -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.4.1.slim.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/all.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
</head>
<body class="d-flex flex-column h-100">
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand text-monospace" href="{{ url_for('main.home') }}">{{ app_name }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/admin"><i class="fas fa-tools"></i> Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.recipients_list') }}"><i class="fas fa-mail-bulk"></i>
                        Destinataires</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.persons') }}"><i class="fas fa-users"></i> Arrivées
                        déclarées</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <a class="btn btn-success my-2 my-sm-0" href="{{ url_for('main.person_add') }}"><i
                        class="fas fa-user-plus"></i>
                    Déclarer une
                    nouvelle arrivée</a>
            </form>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="footer mt-auto py-3 bg-dark text-center">
    <div class="container text-muted text-monospace">
        <p>Application OpenSource développée avec <i class="far fa-heart"></i> en <i class="fab fa-python"></i> par Frédéric CLOITRE &
            pour la LPO Auvergne-Rhône-Alpes<br>
            2019<br>
            <a href="https://framagit.org/lpoaura/auto_email_sender" targer="_blank" title="Lien vers le code source"><i
                    class="fab fa-gitlab"></i> CodeSource</a> | version {{version}}</span>
        </p>
    </div>
</footer>
</body>

</html>

app/templates/person.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<h1><i class="fa fa-user"></i> {% block title %}Nouvelle arrivée enregistrée{% endblock %}</h1>
{%endblock%}

<table>
    <tbody>
    {% for key, segment in person.items()%}
    <tr>
        <td>{{ key }}</td>
        <td>{{ segment }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{%endblock%}

app/templates/person_form.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<div class="row">
    <h1><i class="fa fa-user-plus"></i> {% block title %}Ajout d'un nouvel arrivant{% endblock %}</h1>
    {% endblock %}
    <!--    {% from "_helpers.html" import render_field %}-->
    <!--    {% with messages = get_flashed_messages() %}-->
    <!--    {% if messages %}-->
    <!--    {% for message in messages %}-->
    <!--    <div class="alert alert-danger">{{ message }}</div>-->
    <!--    {% endfor %}-->
    <!--    {% endif %}-->
    <!--    {% endwith %}-->

</div>
<div class="row">
    <div class="col-md-4">
        <div class="alert alert-info">
            <h3><i class="fas fa-info-circle"></i> Note</h3>
            <p>Ce formulaire est à renseigner pour toutes les arrivées de nouveau/nouvelle collègue, indépendamment du
                type de contrat. Merci de le renseigner au moins 2 semaines avant le début de la mission. Son
                remplissage permet
                la génération automatique de messages pour:
            <ul>
                {% for recipient in recipients %}
                <li>{{recipient.email}} : {{recipient.subject}}</li>
                {% endfor %}
            </ul>
            </p>
        </div>
    </div>
    <div class="col-md-8">
        <h3><i class="fas fa-user-edit"></i> Formulaire de déclaration</h3>
        <form method="POST" action="{{url_for('main.person_add')}}">
            {{ form.hidden_tag() }}
            {% for field in form if field.widget.input_type != 'hidden' %}
            <div class="form-group row">
                {% if field.errors %}
                <div class="has-error">
                    {{ field.label(class='col-sm-4 col-form-label') }}
                    <div class="col-sm-8">
                        {{ field }}
                    </div>
                </div>
                <span style="color: red;">{% for error in field.errors %}{{ error }}{% if not loop.last %}<br/>{% endif %}{% endfor %}</span>
                {% else %}
                {{ field.label(class='col-sm-4 col-form-label') }}
                <div class="col-sm-8">
                    {{ field }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <div class="text-right">
                <input type="submit" value="Valider" class="btn btn-success btn-block">
            </div>
            <script>
                $('.datepicker').datepicker({
                    format: 'yyyy-mm-dd',
                    language: "fr",
                    calendarWeeks: true,
                    todayHighlight: true
                });
            </script>
        </form>
    </div>

</div>
{% endblock %}

app/templates/persons.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<div class="row">
    <div class="col-xs-12 col-md-6">
        <h1><i class="fa fa-users"></i> {% block title %}Nouvelles arrivées saisies{% endblock %}</h1>
    </div>
    <div class="col-xs-12 col-md-6">
        <div class="text-right">
            <a class="btn btn-success" href="{{ url_for('main.person_add') }}"><i class="fas fa-user-plus"></i>
                Déclarer une nouvelle arrivée</a>
        </div>
    </div>
</div>
{%endblock%}
<table id="persons" class="table table-condensed table-responsive">
    <thead>
    <tr>
        {% for key in persons[0].keys() %}
        <th scope="col">{{ key }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for person in persons %}
    <tr>
        {% for value in person.values() %}
        <td>{{ value }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>
<script type="text/javascript">

    $('#persons').DataTable();

</script>
{%endblock%}

app/templates/problem.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<div class="row">
    <h1><i class="fa fa-info-circle"></i> {% block title %}Houston, we've got a problem{% endblock %}</h1>
    {%endblock%}
</div>
<div class="row">
    {% from "_helpers.html" import render_field %}


</div>
{% endblock %}

app/templates/recipient_form.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<div class="row">
    <h1><i class="fa fa-mail-bulk"></i> {% block title %}Ajout d'un nouveau destinataire{% endblock %}</h1>
    {%endblock%}

</div>
<div class="row">

    <div class="col-md-4">
        <div class="alert alert-info">
            <h3><i class="fas fa-info-circle"></i> Note</h3>
            <p>Les contenus des mails sont automatiquement générés à partir des modèles que vous créerez ici. Pour ce
                faire, il faut les indiquer dans le Sujet <code>subject</code> et/ou dans le corps du texte
                <code>body</code>. Ces variables doivent obligatoirement être entourées d'accolades. A titre d'exemple,
                le corps de texte suivant <code>Le salarié {name} {surname}...</code> , ou <code>name</code> est <i>MANCEL</i>
                et <code>surname</code> est <i>Benoit</i> donnera ainsi un mail contenant le message suivant <code>Le
                    salarié MANCEL Benoit...</code>
            <ul>
            {% for v in var %}
                <li>
                    {{v.doc}}&nbsp;: <code>{{'{'+v.var+'}'}}</code>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-md-8">
        <h3><i class="fas fa-user-edit"></i> Formulaire de déclaration</h3>
        <form method="POST" action="{{url_for('main.recipient_add')}}">
            {% for field in form if field.widget.input_type != 'hidden' %}
            <div class="form-group row">
                {% if field.errors %}
                <div class="has-error">
                    {{ field.label(class='col-sm-4 col-form-label') }}
                    <div class="col-sm-8">
                        {{ field }}
                    </div>
                </div>
                <span style="color: red;">{% for error in field.errors %}{{ error }}{% if not loop.last %}<br/>{% endif %}{% endfor %}</span>
                {% else %}
                {{ field.label(class='col-sm-4 col-form-label') }}
                <div class="col-sm-8">
                    {{ field }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <div class="text-right">
                <input type="submit" value="Valider" class="btn btn-success btn-block">
            </div>
        </form>
    </div>

</div>
{% endblock %}

app/templates/recipients.html
{%extends "main.html"%}
{%block content %}
{% block header %}
<div class="row">
    <div class="col-xs-12 col-md-6">
        <h1><i class="fas fa-mail-bulk"></i>{% block title %}Destinataires{% endblock %}</h1>
    </div>
    <div class="col-xs-12 col-md-6">
        <div class="text-right">
            <a class="btn btn-success" href="{{ url_for('main.recipient_add') }}"><i class="fas fa-mail-bulk"></i>
                Ajouter un
                nouveau destinataire</a>
        </div>
    </div>

    {%endblock%}
</div>
<div class="row">
    <div class="col">
        {% if recipients|length > 0 %}
        <table id="persons" class="table table-condensed table-responsive">

            <thead>
            <tr>
                {% for key in recipients[0].keys() %}
                <th scope="col">{{ key }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for recipient in recipients %}
            <tr>
                {% for value in recipient.values() %}
                <td>{{ value }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <script type="text/javascript">

            $('#persons').DataTable();

        </script>
        {% else %}
        <div class="alert alert-warning">Aucun destinataire</div>
        {% endif %}

    </div>
</div>
{%endblock%}